# Generated by Django 3.2.4 on 2021-06-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=15, unique=True)),
                ('vehicle_type', models.CharField(choices=[('C', 'Car'), ('T', 'Truck'), ('M', 'Motorcycle')], default='C', max_length=2)),
                ('make', models.CharField(max_length=15)),
                ('model', models.CharField(max_length=15)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('seat_capacity', models.PositiveBigIntegerField(blank=True, null=True)),
                ('roof_rack_availability', models.BooleanField(default=False)),
                ('haul_capacity', models.PositiveBigIntegerField(blank=True, null=True)),
                ('sidecar_availability', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
